server:
  application:
    name: dubbo-springboot-demo-provider
  port: 9000


# dubbo 配置
# 协议
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    id: dubbo
    name: dubbo
    # （ -1 表示自增端口，从 20880 开始）
    port: -1

  # dubbo连接nacos的地址
  registry:
      address: nacos://127.0.0.1:8848
    # Dubbo3 默认采用 “应用级服务发现 + 接口级服务发现” 的双注册模式，因此会发现应用级服务（应用名）和接口级服务（接口名）
    # 同时出现在 Nacos 控制台，可以通过配置 dubbo.registry.register-mode=instance/interface/all 来改变注册行为。
      registry-mode: interface

