server:
  application:
    name: dubbo-springboot-demo-consumer
  port: 8000

dubbo:
  application:
    name: dubbo-springboot-demo-consumer
  protocol:
    id: dubbo
    name: dubbo

  # Dubbo 消费端订阅服务端的应用名，多个服务提供者用逗号分隔
  # 这里订阅"自己"，会被忽略掉，请根据实际情况添加
  cloud:
    subscribe: dubbo-springboot-demo-provider

  #Dubbo3.0.0版本以后，增加了是否注册消费者的参数，如果需要将消费者注册到nacos注册中心上，
  #需要将参数(register-consumer-url)设置为true，默认是false。
  registry:
    address: nacos://127.0.0.1:8848?register-consumer-url=true

